### ISSUE TITLE
checkbox_group is missing `checked` attribute

### ISSUE THREAD

**Issue by krns** [petalframework/petal_components#120]

**Comment by mplatts** [comment]
Should be fixed in 0.19.3

https://github.com/petalframework/petal_components/commit/6bb498abf878f1c89215fee0fd4afe0691e568be

**Comment by krns** [comment]
Thanks!

**Comment by krns** [comment]
I should have added some more details about the issue description. To be specific, the `checked` attribute is also missing in `form_field/1`. The following will still not compile:

``elixir
        <.form_field type="checkbox_group" form={@form} field={@field} checked={@checked} />
```

**Comment by krns** [comment]
@mplatts should I create a new issue or would you reopen this one?

**Comment by mplatts** [comment]
Fixed in https://github.com/petalframework/petal_components/releases/tag/v0.19.4
