### ISSUE TITLE
Field of type radio-group does not apply 'checked' attribute when using v2 Forms

### ISSUE THREAD

**Issue by gtaranti** [petalframework/petal_components#199]
I was using 'radio_group' type field with **Forms v1** and there was the  correct behaviour :
```
  <.form_field type="radio_group" form={@form} layout={:row} field={:rating} label="Rating"
          options={[
            {"1", "1"},
            {"2", "2"},
            {"3", "3"},
            {"4", "4"},
            {"5", "5"}
          ]}
        />
```

After updating to **Forms v2** and converting the above code to :
```
        <.field type="radio-group" group_layout="row" field={@form[:rating]} label="Rating"
          options={[
            {"1", "1"},
            {"2", "2"},
            {"3", "3"},
            {"4", "4"},
            {"5", "5"}
          ]}
        />
```

The result is that when a form is populated with existing data the respective radio control is not 'checked' when the option is set.

Maybe related to #197

**Comment by mplatts** [comment]
Thanks! Should be fixed in v1.2.6

**Comment by gtaranti** [comment]
Hey! This is still not working as expected.
If an option is set when the form is loading with data, the radio control does not reflect that. (i.e. it does not set the 'checked' attribute)
I have checked on Firefox, Safari and Chrome.

**Comment by mplatts** [comment]
Hmm can you give a rough outline of your code? For me the Phoenix.HTML.FormField has a value of "2", and that is showing for me


```html
<% IO.inspect(@form[:radio_group]) %>

    <.field
      type="radio-group"
      field={@form[:radio_group]}
      group_layout="row"
      options={[{"Option 1", "1"}, {"Option 2", "2"}, {"Option 3", "3"}]}
    />
```

```elixir
%Phoenix.HTML.FormField{
  ...
  value: "2"
}
```

<img width="315" alt="CleanShot 2023-05-26 at 16 04 30@2x" src="https://github.com/petalframework/petal_components/assets/184383/0b8f7a17-beeb-491b-8bc5-ba654c6c4673">

**Comment by gtaranti** [comment]
I set a gh repo that you could check : https://github.com/gtaranti/p172
There you could visit http://localhost:4000/test

Sample data have 'rating' field populated, but it's not showing in the form.

**Comment by mplatts** [comment]
Thanks - seems when the value is an integer it didn't work. Works in v1.2.7
